spring:
  jpa:
    open-in-view: false
    properties:
      hibernate:
        hbm2ddl.auto: none
        default_batch_fetch_size: 100

---
spring.config.activate.on-profile: local

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: create
  h2:
    console:
      enabled: true

storage:
  datasource:
    batch-core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: batch-core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true

---
spring.config.activate.on-profile: local-dev
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#        connection.provider_disables_autocommit: true
#        temp.use_jdbc_metadata_defaults: false
#        jdbc.lob.non_contextual_creation: true

storage:
  datasource:
    batch-core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${STORAGE_DATABASE_CORE_DB_URL}
      username: ${STORAGE_DATABASE_CORE_DB_USERNAME}
      password: ${STORAGE_DATABASE_CORE_DB_PASSWORD}
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

---
spring.config.activate.on-profile: dev

storage:
  datasource:
    batch-core:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${STORAGE_DATABASE_CORE_DB_URL}/${STORAGE_DATABASE_CORE_DB_NAME}
      username: ${STORAGE_DATABASE_CORE_DB_USERNAME}
      password: ${STORAGE_DATABASE_CORE_DB_PASSWORD}
      data-source-properties:
        socketTimeout: 3000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false

---
spring.config.activate.on-profile: staging

---
spring.config.activate.on-profile: live