version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/barlow-server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/dev/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/dev/deploy.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/dev/healthCheck.sh
      timeout: 60
      runas: ubuntu
