version: 0.2

phases:
  build:
    commands:
      - echo Build Started on `date`
      - chmod +x ./gradlew
      - ./gradlew :app:api:clean :app:api:build -x test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo $(basename ./app/api/build/libs/*.jar)
      - pwd

artifacts:
  files:
    - appspec.yml
    - app/api/build/libs/*.jar
    - scripts/dev/**
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/caches/**/*'