### 게스트 회원 가입
POST http://localhost:8080/api/v1/auth/guest/signup
Content-Type: application/json

{
  "deviceOs": "ios",
  "deviceId": "deviceId",
  "deviceToken": "deviceToken",
  "nickname": "nickname"
}

###
POST http://localhost:8080/api/v1/auth/guest/login
Content-Type: application/json

{
  "deviceOs": "ios",
  "deviceId": "deviceId",
  "deviceToken": "deviceToken"
}
