#!/bin/bash
BASE_PATH="/home/ubuntu/barlow-server"

CURRENT_TIME=$(date +%c)

BUILD_JAR_FILE=$(ls $BASE_PATH/*.jar)
JAR_NAME=$(basename "$BUILD_JAR_FILE")
echo "$CURRENT_TIME > build 파일명: $JAR_NAME"

LOG_PATH="$BASE_PATH/log"
DEPLOY_LOG="$LOG_PATH/deploy.log"
APP_LOG="$LOG_PATH/nohup.out"

echo "$CURRENT_TIME >  build 파일 복사" >> $DEPLOY_LOG
DEPLOY_PATH=$BASE_PATH/deploy-jar/
cp "$BUILD_JAR_FILE" $DEPLOY_PATH

echo "$CURRENT_TIME > barlow-api-server-deploy.jar 교체" >> $DEPLOY_LOG
CP_JAR_PATH=$DEPLOY_PATH$JAR_NAME
APPLICATION_JAR_NAME=barlow-api-server-deploy.jar
APPLICATION_JAR=$DEPLOY_PATH$APPLICATION_JAR_NAME

echo "$CURRENT_TIME > 심볼릭 링크 설정" >> $DEPLOY_LOG
ln -Tfs "$CP_JAR_PATH" $APPLICATION_JAR

source /home/ubuntu/.profile

SPRING_PROFILES_ACTIVE="dev"
LOG4J_CONTEXT_SELECTOR="org.apache.logging.log4j.core.async.AsyncLoggerContextSelector"

SENTRY_ENVIRONMENT=$SPRING_PROFILES_ACTIVE nohup java -jar \
  -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE \
  -DSTORAGE_DATABASE_CORE_DB_URL="$STORAGE_DATABASE_CORE_DB_URL" \
  -DSTORAGE_DATABASE_CORE_DB_NAME="$STORAGE_DATABASE_CORE_DB_NAME" \
  -DSTORAGE_DATABASE_CORE_DB_USERNAME="$STORAGE_DATABASE_CORE_DB_USERNAME" \
  -DSTORAGE_DATABASE_CORE_DB_PASSWORD="$STORAGE_DATABASE_CORE_DB_PASSWORD" \
  -DSUPPORT_ALERT_SLACK_WEBHOOK_URL="$SUPPORT_ALERT_SLACK_WEBHOOK_URL" \
  -DSENTRY_DSN="$SENTRY_DSN" \
  -DJWT_CRYPTO_PRIVATE_KEY="$JWT_CRYPTO_PRIVATE_KEY" \
  -DJWT_CRYPTO_PUBLIC_KEY="$JWT_CRYPTO_PUBLIC_KEY" \
  -DLog4jContextSelector=$LOG4J_CONTEXT_SELECTOR \
  -Dlog4j2.enable.threadlocals=true \
  -Dlog4j2.enable.direct.encoders=true \
  "$APPLICATION_JAR" > $APP_LOG 2>&1 &

echo "$CURRENT_TIME > build jar 파일 실헹" >> $DEPLOY_LOG
